package com.juneyaoair.sms;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.7.18 2016-08-25T15:12:04.854+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "SmService", wsdlLocation = "http://172.20.70.115/SmService.asmx?wsdl", targetNamespace = "http://tempuri.org/")
public class SmService extends Service {

	public final static URL WSDL_LOCATION;

	public final static QName SERVICE = new QName("http://tempuri.org/", "SmService");
	public final static QName SmServiceSoap12 = new QName("http://tempuri.org/", "SmServiceSoap12");
	public final static QName SmServiceSoap = new QName("http://tempuri.org/", "SmServiceSoap");
	static {
		URL url = null;
		try {
			url = new URL("http://172.20.70.115/SmService.asmx?wsdl");
		} catch (MalformedURLException e) {
			java.util.logging.Logger.getLogger(SmService.class.getName()).log(java.util.logging.Level.INFO,
					"Can not initialize the default wsdl from {0}", "http://172.20.70.115/SmService.asmx?wsdl");
		}
		WSDL_LOCATION = url;
	}

	public SmService(URL wsdlLocation) {
		super(wsdlLocation, SERVICE);
	}

	public SmService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public SmService() {
		super(WSDL_LOCATION, SERVICE);
	}

	// //This constructor requires JAX-WS API 2.2. You will need to endorse the
	// 2.2
	// //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS
	// 2.1
	// //compliant code instead.
	// public SmService(WebServiceFeature ... features) {
	// super(WSDL_LOCATION, SERVICE, features);
	// }
	//
	// //This constructor requires JAX-WS API 2.2. You will need to endorse the
	// 2.2
	// //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS
	// 2.1
	// //compliant code instead.
	// public SmService(URL wsdlLocation, WebServiceFeature ... features) {
	// super(wsdlLocation, SERVICE, features);
	// }
	//
	// //This constructor requires JAX-WS API 2.2. You will need to endorse the
	// 2.2
	// //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS
	// 2.1
	// //compliant code instead.
	// public SmService(URL wsdlLocation, QName serviceName, WebServiceFeature
	// ... features) {
	// super(wsdlLocation, serviceName, features);
	// }

	/**
	 * 
	 * @return returns SmServiceSoap
	 */
	@WebEndpoint(name = "SmServiceSoap12")
	public SmServiceSoap getSmServiceSoap12() {
		return super.getPort(SmServiceSoap12, SmServiceSoap.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *            on the proxy. Supported features not in the
	 *            <code>features</code> parameter will have their default
	 *            values.
	 * @return returns SmServiceSoap
	 */
	@WebEndpoint(name = "SmServiceSoap12")
	public SmServiceSoap getSmServiceSoap12(WebServiceFeature... features) {
		return super.getPort(SmServiceSoap12, SmServiceSoap.class, features);
	}

	/**
	 * 
	 * @return returns SmServiceSoap
	 */
	@WebEndpoint(name = "SmServiceSoap")
	public SmServiceSoap getSmServiceSoap() {
		return super.getPort(SmServiceSoap, SmServiceSoap.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *            on the proxy. Supported features not in the
	 *            <code>features</code> parameter will have their default
	 *            values.
	 * @return returns SmServiceSoap
	 */
	@WebEndpoint(name = "SmServiceSoap")
	public SmServiceSoap getSmServiceSoap(WebServiceFeature... features) {
		return super.getPort(SmServiceSoap, SmServiceSoap.class, features);
	}

}
