package com.usky.sms.service;

import com.usky.sms.core.BaseDao;

public class ServiceDao extends BaseDao<ServiceDO> {

	public ServiceDao() {
		super(ServiceDO.class);
	}

	public static final String[][] services = {
			// actionItem
			{ "query", "getActionItemToDoStatistics", "actionItem", "getActionItemToDoStatistics" },
			{ "query", "getActionItemConfirmMen", "actionItem", "getActionItemConfirmMen" },
			{ "query", "getActionItemAuditors", "actionItem", "getActionItemAuditors" },
			{ "query", "exportActionItemsToExcel", "actionItem", "exportActionItemsToExcel" },
			{ "modify", "confirmActionItems", "actionItem", "confirmActionItems" },
			{ "modify", "confirmRejectedActionItems", "actionItem", "confirmRejectedActionItems" },
			{ "modify", "auditPassActionItems", "actionItem", "auditPassActionItems" },
			{ "modify", "auditRejectedActionItems", "actionItem", "auditRejectedActionItems" },
			{ "modify", "distributeActionItems", "actionItem", "distributeActionItems" },
			{ "modify", "executeActionItem", "actionItem", "executeActionItem" },
			{ "query", "getCheckOverdueInfo", "auditReport", "getCheckOverdueInfo" },
			{ "query", "getAuditOverdueInfo", "auditReport", "getAuditOverdueInfo" },
			// activity
			{ "modify", "copyactivitysecurityscheme", "activity", "copyActivitySecurityScheme" },
			{ "modify", "transform", "activity", "transform" },
			{ "query", "getInfoTypeCntByDay", "activity", "getInfoTypeCntByDay" },
			{ "query", "getStaffRptCntByDay", "activity", "getStaffRptCntByDay" },
			{ "modify", "importActivitiesFromExcel", "activity", "importActivitiesFromExcel" },
			{ "modify", "submitEmReport", "activity", "submitEmReport" },
			{ "modify", "submitAircraftCommanderReport", "activity", "submitAircraftCommanderReport" },
			{ "modify", "distributeActivity", "activity", "distributeActivity" },
			{ "modify", "distributeActivityThroughDept", "activity", "distributeActivityThroughDept" },
			{ "query", "getactivitycreatingconfig", "activity", "getActivityCreatingConfig" },
			{ "query", "getactivitycreatingtype", "activity", "getActivityCreatingType" },
			{ "query", "getactivitycreatingunit", "activity", "getActivityCreatingUnit" },
			{ "query", "getactivityeditingconfig", "activity", "getActivityEditingConfig" },
			{ "query", "getactivityoperation", "activity", "getActivityOperation" },
			{ "query", "getactivitysecuritylevels", "activity", "getActivitySecurityLevels" },
			{ "query", "getactivitystatuscategory", "activity", "getActivityStatusCategory" },
			{ "query", "getactivitytransformconfig", "activity", "getActivityTransformConfig" },
			{ "query", "getactivitytransformtype", "activity", "getActivityTransformType" },
			{ "query", "getactivitytypeschemeselectionforunit", "activity", "getActivityTypeSchemeSelectionForUnit" },
			{ "query", "getactivityviewconfig", "activity", "getActivityViewConfig" },
			{ "query", "getactivityworkflowconfig", "activity", "getActivityWorkflowConfig" },
			{ "query", "exportActivitiesToExcel", "activity", "exportActivitiesToExcel" },
			{ "query", "fuzzySearchActivityInfos", "activity", "fuzzySearchActivityInfos" },
			{ "query", "getEmReportDeatil", "activity", "getEmReportDeatil" },
			{ "query", "getActivityBaseInfo", "activity", "getActivityBaseInfo" },
			{ "query", "exportActivityToPdf", "activity", "exportActivityToPdf" },
			{ "query", "getDistributedActivityProcessors", "activity", "getDistributedActivityProcessors" },
			{ "query", "getDefectTypeList", "activity", "getDefectTypeList" },
			{ "query", "getMeasureTypeList", "activity", "getMeasureTypeList" },
			{ "query", "getStaffReportStatusDist", "activity", "getStaffReportStatusDist" },
			{ "query", "getInfoTypeCntByMonth", "activity", "getInfoTypeCntByMonth" },
			{ "query", "getStaffRptCntByMonth", "activity", "getStaffRptCntByMonth" },
			{ "query", "getStaffRptCntByDept", "activity", "getStaffRptCntByDept" },
			{ "query", "getInfoRptOverdueList", "activity", "getInfoRptOverdueList" },
			{ "query", "getToDoActivities", "activity", "getToDoActivities" },
			{ "query", "getInfoRptOverdueDist", "activity", "getInfoRptOverdueDist" },
			{ "query", "getActionItemOverdue", "activity", "getActionItemOverdue" },
			{ "query", "getStaffRptOverdueList", "activity", "getStaffRptOverdueList" },
			{ "query", "getAllRptCntByDept", "activity", "getAllRptCntByDept" },
			// aircraftModel
			{ "modify", "modifyAircraftModel", "aircraftModel", "modifyAircraftModel" },
			{ "query", "getFamilycodeBySearch", "aircraftModel", "getFamilycodeBySearch" },
			{ "query", "getManufacturerBySearch", "aircraftModel", "getManufacturerBySearch" },
			{ "query", "getAircraftModelCodeBySearch", "aircraftModel", "getAircraftModelCodeBySearch" },
			// assessmentProject
			{ "query", "getAssessmentProjects", "assessmentProject", "getAssessmentProjects" },
			// report
			{ "query", "getByIncidentType", "report", "getByIncidentType" },
			{ "query", "getSeverityScore", "report", "getSeverityScore" },
			{ "query", "countActivity", "report", "countActivity" },
			{ "query", "getActionItemByUser", "report", "getActionItemByUser" },
			{ "query", "systemLine", "report", "systemLine" },
			{ "query", "getToDoStatistics", "report", "getToDoStatistics" },
			// report 新报表
			{ "query", "getConsequenceRadar", "report", "getConsequenceRadar" },
			{ "query", "getConsequenceLine", "report", "getConsequenceLine" },
			{ "query", "getInsecurityPie", "report", "getInsecurityPie" },
			{ "query", "getInsecurityTiao", "report", "getInsecurityTiao" },
			{ "query", "getThreatPie", "report", "getThreatPie" },
			{ "query", "getThreatTiao", "report", "getThreatTiao" },
			{ "query", "getErrorPie", "report", "getErrorPie" },
			{ "query", "getErrorTiao", "report", "getErrorTiao" },
			{ "query", "getScoreByThreatPie", "report", "getScoreByThreatPie" },
			{ "query", "getScoreByThreatTiao", "report", "getScoreByThreatTiao" },
			{ "query", "getScoreByErrorPie", "report", "getScoreByErrorPie" },
			{ "query", "getScoreByErrorTiao", "report", "getScoreByErrorTiao" },
			{ "query", "getConsequenceByInsecurity", "report", "getConsequenceByInsecurity" },
			{ "query", "getInsecurityLine", "report", "getInsecurityLine" },
			{ "query", "getThreatLine", "report", "getThreatLine" },
			{ "query", "getErrorLine", "report", "getErrorLine" },
			{ "query", "getEventBySystem", "report", "getEventBySystem" },
			{ "query", "getSeverityByFliter", "report", "getSeverityByFliter" },
			{ "query", "getEventTypeFliterPie", "report", "getEventTypeFliterPie" },
			{ "query", "getEventTypeFliterTiao", "report", "getEventTypeFliterTiao" },
			{ "query", "getFlightPhaseFliterPie", "report", "getFlightPhaseFliterPie" },
			{ "query", "getFlightPhaseFliterTiao", "report", "getFlightPhaseFliterTiao" },
			{ "query", "getlabelFliter", "report", "getlabelFliter" },
			{ "query", "getEventTypeLine", "report", "getEventTypeLine" },
			{ "query", "getlabelLineFliter", "report", "getlabelLineFliter" },
			{ "query", "getFlightPhaseLineFliter", "report", "getFlightPhaseLineFliter" },
			{ "query", "getAirportFliterPie", "report", "getAirportFliterPie" },
			{ "query", "getAirportFliterTiao", "report", "getAirportFliterTiao" },
			{ "query", "getOrganizationByFliter", "report", "getOrganizationByFliter" },
			{ "query", "getInsecurityGauge", "report", "getInsecurityGauge" },
			{ "query", "getOrganizationLineFliter", "report", "getOrganizationLineFliter" },
			{ "query", "getEventEmpReport", "report", "getEventEmpReport" },
			{ "query", "getUnitEmpReport", "report", "getUnitEmpReport" },
			{ "query", "getAircraftTypePie", "report", "getAircraftTypePie" },
			{ "query", "getAircraftTypeTiao", "report", "getAircraftTypeTiao" },
			{ "query", "getAircraftTypeLine", "report", "getAircraftTypeLine" },

			{ "query", "getInsecurityByConsequence", "report", "getInsecurityByConsequence" },
			// completionInst
			{ "modify", "updateCompletionInsts", "completionInst", "updateCompletionInsts" },

			// dailySafetyWorkStatus
			{ "modify", "modifyDailySafetyWorkStatus", "dailySafetyWorkStatus", "modifyDailySafetyWorkStatus" },
			{ "query", "getDailySafetyWorkStatus", "dailySafetyWorkStatus", "getDailySafetyWorkStatus" },
			{ "query", "fuzzySearchDailySafetyWorkStatusInfos", "dailySafetyWorkStatus", "fuzzySearchDailySafetyWorkStatusInfos" },
			// dashboard
			{ "query", "getFavorDashboard", "dashboard", "getFavorDashboard" },
			{ "query", "getMyDashboard", "dashboard", "getMyDashboard" },
			{ "query", "getHotDashboard", "dashboard", "getHotDashboard" },
			{ "query", "getShareDashboard", "dashboard", "getShareDashboard" },
			{ "query", "getDashboardDetail", "dashboard", "getDashboardDetail" },
			{ "modify", "favorDashBoard", "dashboard", "favorDashBoard" },
			// dictionary
			{ "query", "getManageTemDictionaryPermission", "dictionary", "getManageTemDictionaryPermission" },
			{ "modify", "publishuserdefaultsetting", "dictionary", "publishUserDefaultSetting" },
			// directory
			{ "modify", "modifyDirectory", "directory", "modifyDirectory" },
			{ "query", "getDirectorys", "directory", "getDirectorys" },
			{ "query", "getSafetyLibraryPermissions", "directory", "getSafetyLibraryPermissions" },
			{ "query", "fuzzySearchDirectoryInfos", "directory", "fuzzySearchDirectoryInfos" },
			{ "query", "fuzzySearchRiskSourceDirectoryInfos", "directory", "fuzzySearchRiskSourceDirectoryInfos" },
			{ "query", "fuzzySearchRiskSourceSectionInfos", "directory", "fuzzySearchRiskSourceSectionInfos" },
			{ "query", "getSafetyInfoType", "directory", "getSafetyInfoType" },
			
			// error
			{ "query", "exportErrorsToExcel", "error", "exportErrorsToExcel" },
			
			// download
			{ "query", "download", "download", "doDefault" },
			// email
			{ "query", "getSmtp", "smtp", "getSmtp" },
			{ "query", "testConnection", "smtp", "testConnection" },
			{ "query", "sendTestEmail", "smtp", "sendTestEmail" },
			{ "query", "sendEmail", "smtp", "sendEmail" },
			{ "query", "getEmails", "email", "getEmails" },
			{ "modify", "sendEmails", "email", "sendEmails" },
			// event
			{ "query", "getallevents", "event", "getAllEvents" },
			// eventAnalysis
			{ "modify", "saveOrUpdateEventAnalysis", "eventAnalysis", "saveOrUpdateEventAnalysis" },
			// field
			{ "modify", "copyactivitytypefieldscreenscheme", "field", "copyActivityTypeFieldScreenScheme" },
			{ "modify", "copyfieldlayout", "field", "copyFieldLayout" },
			{ "modify", "copyfieldlayoutscheme", "field", "copyFieldLayoutScheme" },
			{ "modify", "copyfieldscreen", "field", "copyFieldScreen" },
			{ "modify", "copyfieldscreenscheme", "field", "copyFieldScreenScheme" },
			{ "modify", "setfieldtabmapping", "field", "setFieldTabMapping" },
			{ "modify", "sortfieldscreenlayoutitem", "field", "sortFieldScreenLayoutItem" },
			{ "modify", "sortfieldscreentab", "field", "sortFieldScreenTab" },
			{ "query", "getactivitytypefieldscreenschemeentities", "field", "getActivityTypeFieldScreenSchemeEntities" },
			{ "query", "getallfields", "field", "getAllFields" },
			{ "query", "getfieldlayoutitems", "field", "getFieldLayoutItems" },
			{ "query", "getfieldlayoutschemeentities", "field", "getFieldLayoutSchemeEntities" },
			{ "query", "getfieldscreenschemeitems", "field", "getFieldScreenSchemeItems" },
			{ "query", "getfieldscreentabs", "field", "getFieldScreenTabs" },
			{ "query", "getfieldtabmapping", "field", "getFieldTabMapping" },
			{ "query", "getSearchFields", "field", "getSearchFields" },
			{ "query", "getAllDisplayFields", "field", "getAllDisplayFields" },
			// file
			{ "modify", "upload", "file", "upload" },
			{ "modify", "uploadFiles", "file", "uploadFiles" },
			{ "query", "downloadFiles", "file", "downloadFiles" },
			{ "query", "getFilesBySource", "file", "getFilesBySource" },
			{ "query", "getFtypeByActivityId", "file", "getFtypeByActivityId" },
			{ "query", "getFileTypes", "file", "getFileTypes" },
			// filtermanager
			{ "query", "getFilter", "filtermanager", "getFilter" },
			{ "modify", "favorFiltermanager", "filtermanager", "favorFiltermanager" },
			{ "modify", "copyFiltermanager", "filtermanager", "copyFiltermanager" },
			// FlightInfoService 信息获取
			{ "query", "getBaseInfo", "flightInfo", "getBaseInfo" },
			{ "query", "getFlightInfo", "flightInfo", "getFlightInfo" },
			{ "query", "getAirport", "flightInfo", "getAirport" },
			{ "query", "searchFlightCrew", "flightInfo", "searchFlightCrew" },
			{ "query", "getAircraftInfo", "flightInfo", "getAircraftInfo" },
			{ "query", "getWeather", "flightInfo", "getWeather" },
			{ "query", "getAirportBySearch", "flightInfo", "getAirportBySearch" },
			{ "query", "getAircraftBySearch", "flightInfo", "getAircraftBySearch" },
			{ "query", "getAllTailNO", "flightInfo", "getAllTailNO" },
			{ "query", "getAllFlightNO", "flightInfo", "getAllFlightNO" },
			{ "query", "getAllAirportName", "flightInfo", "getAllAirportName" },
			{ "query", "getAirportInformation", "flightInfo", "getAirportInformation" },
			{ "query", "getAirportPdf", "flightInfo", "getAirportPdf" },
			// geography
			{ "query", "queryGeography", "geography", "queryGeography" },
			{ "modify", "modifyGeography", "geography", "modifyGeography" },
			// history
			{ "query", "stdcomponent.getlog", "history", "getHistory" },
			// label
			{ "query", "getlabels", "label", "getLabels" },
			// matrix
			{ "modify", "updateAll", "matrix", "updateAll" },
			{ "query", "getByMatrix", "matrix", "getByMatrix" },
			// menu
			{ "query", "getmenu", "menu", "getMenu" },
			// message
			{ "modify", "modifyMessage", "message", "modifyMessage" },
			{ "query", "getMessages", "message", "getMessages" },
			{ "query", "getMessageCatagories", "message", "getMessageCatagories" },
			// MethanolService 安全评审
			{ "query", "achieve", "methanolInst", "achieve" },
			{ "modify", "addMethanol", "methanolInst", "addMethanol" },
			{ "query", "getCompletionByAssessmentComment", "methanolInst", "getCompletionByAssessmentComment" },
			{ "modify", "updateReview", "methanolInst", "updateReview" },
			{ "query", "getAllMethanol", "methanolInst", "getAllMethanol" },
			{ "query", "getByUnitName", "methanolInst", "getByUnitName" },
			{ "query", "getMethanolPermissions", "methanolInst", "getMethanolPermissions" },
			{ "query", "getMethanolsByMultiCon", "methanolInst", "getMethanolsByMultiCon" },
			{ "query", "getMethanolsForUnits", "methanolInst", "getMethanolsForUnits" },
			{ "modify", "generateMethanolInst", "methanolInst", "generateMethanolInst" },
			{ "query", "getMethanolById", "methanolInst", "getMethanolById" },
			{ "query", "exportMethanolToPdf", "methanolInst", "exportMethanolToPdf" },
			{ "modify", "updateMethanolInsts", "methanolInst", "updateMethanolInsts" },
			{ "modify", "evalCompletionByMethanolInst", "methanolInst", "evalCompletionByMethanolInst" },
			// modify
			{ "modify", "stdcomponent.add", "modify", "doDefault" },
			{ "modify", "stdcomponent.addall", "modify", "doDefault" },
			{ "modify", "stdcomponent.addextend", "modify", "doDefault" },
			{ "modify", "stdcomponent.update", "modify", "doDefault" },
			{ "modify", "stdcomponent.updateall", "modify", "doDefault" },
			{ "modify", "stdcomponent.updateextend", "modify", "doDefault" },
			{ "modify", "stdcomponent.delete", "modify", "doDefault" },
			// notification
			{ "modify", "copynotificationscheme", "notification", "copyNotificationScheme" },
			{ "query", "getnotificationschemeitems", "notification", "getNotificationSchemeItems" },
			// org
			{ "modify", "updateAllOrg", "organization", "updateAllOrg" },
			{ "modify", "modifyOrganization", "organization", "modifyOrganization" },
			{ "query", "getSysTemByUser", "organization", "getSysTemByUser" },
			{ "query", "getOrganizationsByParent", "organization", "getOrganizationsByParent" },
			{ "query", "getOrganizationMembers", "organization", "getOrganizationMembers" },
			{ "query", "getAddableUsersForOrganization", "organization", "getAddableUsersForOrganization" },
			{ "query", "getAllOrganizations", "organization", "getAllOrganizations" },
			{ "query", "getOrganizationByUserId", "organization", "getOrganizationByUserId" },
			{ "query", "getByUnit", "organization", "getByUnit" },
			{ "query", "getByUnitforEm", "organization", "getByUnitforEm" },
			{ "query", "getOrganizationsByViewUnit", "organization", "getOrganizationsByViewUnit" },
			// outview
			{ "modify", "uploadLogo", "logo", "uploadLogo" },
			{ "modify", "backLogo", "logo", "backLogo" },
			{ "query", "getNavigation", "navigation", "getNavigation" },
			{ "query", "getSiteFlag", "logo", "getSiteFlag" },
			{ "query", "getColor", "color", "getColor" },
			{ "query", "getToolColor", "toolColor", "getToolColor" },
			// permission
			{ "modify", "copypermissionscheme", "permission", "copyPermissionScheme" },
			{ "query", "getpermissionschemepermissionset", "permission", "getPermissionSchemePermissionSet" },
			{ "query", "getURGP", "permission", "getURGP" },
			// plugin
			{ "query", "getplugins", "plugin", "getList" },
			{ "query", "installplugin", "plugin", "installPlugin" },
			{ "query", "uninstallplugin", "plugin", "uninstallPlugin" },
			// query
			{ "query", "stdcomponent.getbysearch", "query", "doDefault" },
			{ "query", "stdcomponent.getbyid", "query", "doDefault" },
			{ "query", "stdcomponent.getbyids", "query", "doDefault" },
			{ "query", "echo", "query", "doDefault" },
			// renderer
			{ "query", "getrendererbyfieldlayoutitem", "renderer", "getRendererByFieldLayoutItem" },
			// risk
			{ "query", "generateReport", "risk", "generateReport" },
			{ "query", "getActivityInfoOfRisk", "risk", "getActivityInfoOfRisk" },
			{ "query", "getRiskAnalysisPerson", "risk", "getRiskAnalysisPerson" },
			{ "modify", "addAirlineInfo", "risk", "addAirlineInfo" },
			{ "modify", "addRiskTaskSetting", "risk", "addRiskTaskSetting" },
			{ "modify", "publish", "risk", "publish" },
			{ "modify", "updateAirlineInfo", "risk", "updateAirlineInfo" },
			{ "modify", "updateRiskTaskSetting", "risk", "updateRiskTaskSetting" },
			// scoreStandard
			{ "query", "testEval", "scoreStandard", "testEval" },
			// scoreStandardDetail
			{ "query", "testExpression", "scoreStandardDetail", "testExpression" },
			{ "modify", "addScoreStandardDetail", "scoreStandardDetail", "addScoreStandardDetail" },
			// section
			{ "modify", "modifySection", "section", "modifySection" },
			
			// search
			{ "query", "getsearchtemplates", "searchTemplate", "getSearchTemplate" },
			// solr
			{ "modify", "solr.addcore", "solr", "addCore" },
			{ "modify", "solr.synchronize", "solr", "synchronize" },
			// subscribe
			{ "query", "getSysTime", "subscribe", "getSysTime" },
			{ "query", "excuteImmediately", "subscribe", "excuteImmediately" },
			// synchronize
			{ "modify", "synchronization", "synchronize", "synchronize" },
			{ "modify", "synchronizeActivity", "synchronize", "synchronizeActivity" },
			{ "modify", "synchronizeActivityWithThreads", "synchronize", "synchronizeActivityWithThreads" },
			// systemAnalysis
			{ "query", "getSystemAnalysisFactorBySearch", "systemAnalysis", "getSystemAnalysisFactorBySearch" },
			// tem
			{ "modify", "adderror", "tem", "addError" },
			{ "modify", "addthreat", "tem", "addThreat" },
			{ "modify", "removeerror", "tem", "removeError" },
			{ "modify", "removethreat", "tem", "removeThreat" },
			{ "modify", "savecontrolmeasures", "tem", "saveControlMeasures" },
			{ "query", "calculateByTerm", "tem", "calculateByTerm" },
			{ "query", "calculateLine", "tem", "calculateLine" },
			{ "query", "calculateLineByItem", "tem", "calculateLineByItem" },
			{ "query", "calculateInsecurity", "tem", "calculateInsecurity" },
			{ "query", "getTOrRforActivity", "tem", "getTOrRforActivity" },

			{ "query", "calculateByMultiCon", "tem", "calculateByMultiCon" },
			{ "query", "getInsecurityList", "tem", "getInsecurityList" },
			{ "query", "calculateByMultiConForThreatAndError", "tem", "calculateByMultiConForThreatAndError" },
			{ "query", "calculateByMultiConOneMonthForThreatAndError", "tem", "calculateByMultiConOneMonthForThreatAndError" },

			{ "query", "getScoreBySysType", "tem", "getScoreBySysType" },
			{ "query", "drawRadar", "tem", "drawRadar" },
			{ "query", "drawLine", "tem", "drawLine" },
			{ "query", "getScoreByUnit", "tem", "getScoreByUnit" },
			{ "query", "drawGaugeByInsecurity", "tem", "drawGaugeByInsecurity" },
			{ "query", "drawGaugeAll", "tem", "drawGaugeAll" },
			
			// threat威胁
			{"query","getRiskColour","threat","getRiskColour"},
			{"query","exportThreatsToExcel","threat","exportThreatsToExcel"},
			{"modify","updateRiskTwoLevels","threat","updateRiskTwoLevels"},
			
			// trainingRecord
			{ "query", "getTrainingRecordPermission", "trainingRecord", "getTrainingRecordPermission" },
			{ "query", "getCertificateType", "trainingRecord", "getCertificateType" },
			{ "query", "getTrainingType", "trainingRecord", "getTrainingType" },
			{ "query", "exportTrainingRecordsToExcel", "trainingRecord", "exportTrainingRecordsToExcel" },
			{ "modify", "saveAllTrainingRecords", "trainingRecord", "saveAllTrainingRecords" },
			// test
			{ "test", "test", "test", "doDefault" },
			// unit
			{ "query", "getrecentunits", "unit", "getRecentUnits" },
			{ "query", "getunitactivitytypescheme", "unit", "getUnitActivityTypeScheme" },
			{ "query", "getunitconfigsummary", "unit", "getUnitConfigSummary" },
			{ "query", "getunitfieldscheme", "unit", "getUnitFieldScheme" },
			{ "query", "getunitroles", "unit", "getUnitRoles" },
			{ "query", "getunits", "unit", "getUnits" },
			{ "query", "getunitscreenscheme", "unit", "getUnitScreenScheme" },
			{ "query", "getUnitsByCurrentUser", "unit", "getUnitsByCurrentUser" },
			{ "query", "getUserUnits", "unit", "getUserUnits" },
			{ "modify", "addactivitytypeschemeforunit", "unit", "addActivityTypeSchemeForUnit" },
			{ "modify", "setunitroles", "unit", "setUnitRoles" },
			// user
			{ "query", "getYxwUser", "user", "getYxwUser" },
			{ "modify", "saveYxwUser", "user", "saveYxwUser" },
			{ "query", "getUserIdNameByGroupId", "user", "getUserIdNameByGroupId" },
			{ "query", "getUserIdNameByGroupName", "user", "getUserIdNameByGroupName" },
			{ "query", "getUserIdNameByGroupKey", "user", "getUserIdNameByGroupKey" },
			{ "query", "getUserIdNameByRoleKey", "user", "getUserIdNameByRoleKey" },
			{ "query", "getUsersByUnitIdsAndRoleIds", "user", "getUsersByUnitIdsAndRoleIds" },
			{ "query", "getUsersByUnitIds", "user", "getUsersByUnitIds" },
			{ "query", "getDeptUsersByRoles", "user", "getDeptUsersByRoles"},
			
			{ "modify", "cancelWatch", "userAssociation", "cancelWatch" },
			{ "query", "getWatchUser", "userAssociation", "getWatchUser" },
			{ "query", "getActivityByUser", "userAssociation", "getActivityByUser" },
			// workflow
			{ "modify", "copyworkflowscheme", "workflow", "copyWorkflowScheme" },
			{ "modify", "operate", "workflow", "operate" },
			{ "query", "getdistributableentities", "workflow", "getDistributableEntities" },
			{ "query", "getworkflowactivitystatuslog", "workflow", "getWorkflowActivityStatusLog" },
			{ "query", "getworkflowbyunitandtype", "workflow", "getWorkflowByUnitAndType" },
			{ "query", "getworkflowschemeentities", "workflow", "getWorkflowSchemeEntities" },
			{ "query", "getWorkflowTemplates", "workflow", "getWorkflowTemplates" },
			{ "query", "getNextStepProcessors", "workflow", "getNextStepProcessors" },
			// qar
			{ "query", "getBoUrl", "qar", "getBoUrl" },
			// QarEventService QAR事件
			{ "query", "getQarEvent", "qarevent", "getQarEvent" },

			// QarEventService QAR事件
			{ "query", "getQarCompany", "qarQuery", "getQarCompany" },
			{ "query", "getQarEventList", "qarQuery", "getQarEventList" },
			{ "query", "getAirportList", "qarQuery", "getAirportList" },
			{ "query", "getAllFieldList", "qarQuery", "getAllFieldList" },

			// audit
			{ "query", "getItemFields", "auditBase", "getItemFields" },
			{ "query", "getItemFieldsData", "auditBase", "getItemFieldsData" },
			{ "query", "getProfessionUserBySearch", "auditBase", "getProfessionUserBySearch" },
			{ "query", "getItemTree", "auditBase", "getItemTree" },
			{ "query", "getItemTreeNode", "auditBase", "getItemTreeNode" },
			{ "query", "getItemByChapter", "auditBase", "getItemByChapter" },
			{ "modify", "addTMPItem", "auditBase", "addTMPItem" },
			{ "query", "getGradeOneAuditors", "auditBase", "getGradeOneAuditors" },
			{ "query", "getMarkByUser", "auditBase", "getMarkByUser" },
			{ "query", "getFirstAuditors", "auditBase", "getFirstAuditors" },
			{ "query", "getGradeTwoAuditors", "auditBase", "getGradeTwoAuditors" },
			{ "query", "getGradeOneManagerAuditors", "auditBase", "getGradeOneManagerAuditors" },
			{ "query", "getTaskManager", "auditBase", "getTaskManager" },
			{ "query", "getItemByTypeAndProfession", "auditBase", "getItemByTypeAndProfession" },
			// auditor
			{ "query", "getAuditors", "auditor", "getAuditors" },
			{ "modify", "uploadAuditorPIC", "auditor", "uploadAuditorPIC" },
			{ "query", "getAuditorInfoById", "auditor", "getAuditorInfoById" },
			{ "query", "getUserInfoById", "auditor", "getUserInfoById" },
			{ "modify", "SaveAuditorTrain", "auditor", "SaveAuditorTrain" },
			{ "modify", "saveAuditorTrainErJi", "auditor", "saveAuditorTrainErJi" },
			{ "query", "getAuditorInfoByUserId", "auditor", "getAuditorInfoByUserId" },
			{ "query", "getAllUsersByUnit", "auditor", "getAllUsersByUnit" },
			// plan
			{ "query", "getPlanByYearAndType", "plan", "getPlanByYearAndType" },
			{ "query", "getAddPlanPermission", "plan", "getAddPlanPermission" },
			{ "query", "getFirstPlanYear", "plan", "getFirstPlanYear" },
			{ "query", "getPlanType", "plan", "getPlanType" },
			{ "query", "getCheckGrade", "plan", "getCheckGrade" },
			{ "query", "checkThirdGradeAuditMaster", "plan", "checkThirdGradeAuditMaster" },
			{ "query", "getCheckInitSearchCondition", "plan", "getCheckInitSearchCondition" },
			{ "modify", "modifyPlanTime", "plan", "modifyPlanTime" },
			// task
			{ "modify", "updateTask", "task", "updateTask" },
			{ "modify", "createTask", "task", "createTask" },
			{ "query", "getAuditTypes", "task", "getAuditTypes" },
			{ "query", "getAuditReport", "task", "getAuditReport" },
			{ "query", "exportAuditReportToPdf", "task", "exportAuditReportToPdf" },
			{ "query", "getTermTaskById", "task", "getTermTaskById" },
			{ "query", "getTaskMenuPermission", "task", "getTaskMenuPermission" },
			{ "query", "getTaskMenuPermissionByUser", "task", "getTaskMenuPermissionByUser" },
			// todoView
			{ "query", "getTodoList", "todoView", "getTodoList" },
			// check
			{ "modify", "updateCheckList", "check", "updateCheckList" },
			{ "query", "getResponsibilityUnits", "check", "getResponsibilityUnits" },
			{ "query", "exportCheckToWord", "check", "exportCheckToWord" },
			{ "query", "getCheckMembers", "check", "getCheckMembers" },
			{ "modify", "saveCheckList", "check", "saveCheckList" },
			// checkList
			{ "query", "getImproveRecordById", "checkList", "getImproveRecordById" },
			{ "modify", "transmitImproveRecord", "checkList", "transmitImproveRecord" },
			{ "modify", "updateImproveRecordStatus", "checkList", "updateImproveRecordStatus" },
			{ "modify", "updateImproveRecordReasonAndMeasure", "checkList", "updateImproveRecordReasonAndMeasure" },
			{ "modify", "commitImproveRecord", "checkList", "commitImproveRecord" },
			{ "modify", "updateImproveRecordCompletion", "checkList", "updateImproveRecordCompletion" },
			{ "modify", "commitImproveRecordCompletion", "checkList", "commitImproveRecordCompletion" },
			{ "modify", "updateAndCloneCheckList", "checkList", "updateAndCloneCheckList" },
			{ "modify", "sendMessageToYanZhengRen", "checkList", "sendMessageToYanZhengRen" },
			{ "query", "getEnumImproveItemStatus", "checkList", "getEnumImproveItemStatus" },
			{ "query", "getEnumTraceItemStatus", "checkList", "getEnumTraceItemStatus" },
			// sheet
			{ "query", "getCheckSheet", "sheet", "getCheckSheet" },
			{ "query", "exportTraceToPDF", "sheet", "exportTraceToPDF" },
			{ "modify", "importItem", "sheet", "importItem" },
			{ "query", "getOrganizationUseSheet", "sheet", "getOrganizationUseSheet" },
			// improve
			{ "query", "getImproveById", "improve", "getImproveById" },
			{ "query", "getTraceById", "improve", "getTraceById" },
			{ "query", "getImproveByTaskId", "improve", "getImproveByTaskId" },
			{ "query", "exportImproveToPdf", "improve", "exportImproveToPdf" },
			{ "query", "exportTraceToPdf", "improve", "exportTraceToPdf" },
			// improveNotice
			{ "query", "getImproveNoticeStatus", "improveNotice", "getImproveNoticeStatus" },
			{ "query", "getImproveNoticeIssueTraceStatus", "improveNotice", "getImproveNoticeIssueTraceStatus" },
			{ "query", "getImproveNoticeById", "improveNotice", "getImproveNoticeById" },
			{ "query", "getImproveNoticeSource", "improveNotice", "getImproveNoticeSource" },
			{ "query", "getImproveNoticeResponsibilityUnits", "improveNotice", "getImproveNoticeResponsibilityUnits" },
			{ "query", "getAddedImproveUnits", "improveNotice", "getAddedImproveUnits" },
			{ "query", "getAllImproveNoticeOperators", "improveNotice", "getAllImproveNoticeOperators" },
			{ "modify", "sendImproveNotice", "improveNotice", "sendImproveNotice" },
			{ "query", "getCreateImproveNoticePermission", "improveNotice", "getCreateImproveNoticePermission" },
			{ "query", "searchImproveNotice", "improveNotice", "searchImproveNotice" },
			{ "query", "getUnitsTree", "improveNotice", "getUnitsTree" },
			{ "query", "getImproveNoticeConfirmMan", "improveNotice", "getImproveNoticeConfirmMan" },
			{ "query", "getAddableImproveNoticeUnits", "improveNotice", "getAddableImproveNoticeUnits" },
			{ "query", "exportImproveNoticeToPdf", "improveNotice", "exportImproveNoticeToPdf" },
			// subImproveNotice
			{ "query", "getSubImproveNoticeById", "subImproveNotice", "getSubImproveNoticeById" },
			{ "query", "exportSubImproveNoticeToPdf", "subImproveNotice", "exportSubImproveNoticeToPdf" },
			// innerPlan
			{ "modify", "innerCreatePlan", "innerPlan", "innerCreatePlan" },
			{ "query", "getErJiZuZhiByUnit", "innerPlan", "getErJiZuZhiByUnit" },
			// validateRisk
			{ "query", "getValidateList", "validateRisk", "getValidateList" },
			{ "modify", "saveFenPeiResult", "validateRisk", "saveFenPeiResult" },
			// rewards
			{ "query", "rewardsGetFlightInfoByActivity", "rewards", "rewardsGetFlightInfoByActivity" },
			{ "query", "getRewardsType", "rewards", "getRewardsType" },
			{ "query", "getRewardsList", "rewards", "getRewardsList" },
			{ "query", "getRewardsById", "rewards", "getRewardsById" },
			{ "query", "getRewardsActivitys", "rewards", "getRewardsActivitys" },
			{ "query", "exportRewardsToExcel", "rewards", "exportRewardsToExcel" },
			{ "query", "getRewardsPermission", "rewards", "getRewardsPermission" },
			// 外部接口 externalInterface
			{ "query", "getActivityByTypeAndCreatedAndUnitZ", "externalInterface", "getActivityByTypeAndCreatedAndUnitZ" },
			{ "query", "getRadarZ", "externalInterface", "getRadarZ" },
			// 系统新增的需求
			{ "query", "getUserBySearchN", "externalInterface", "getUserBySearchN" },
			{ "query", "getUserByOrganizationN", "externalInterface", "getUserByOrganizationN" },
			{ "query", "getUserByRoleN", "externalInterface", "getUserByRoleN" },
			// 20160311新加
			{ "query", "getSeverityByFliterN", "externalInterface", "getSeverityByFliterN" },
			// 移动端接口
			{ "query", "getTaskPad", "pad", "getTaskPad" },
			{ "query", "getTaskPadById", "pad", "getTaskPadById" },
			{ "query", "getQar_event_tongbi", "pad", "getQar_event_tongbi" },
			{ "query", "getTODOCount", "pad", "getTODOCount" },
			{ "modify", "downfile", "pad", "downfile" },
			// 审计报表
			{ "query", "getAuditMap", "auditReport", "getAuditMap" },
			{ "query", "getImproveIssueList", "auditReport", "getImproveIssueList" },
			{ "query", "getCheckListBar", "auditReport", "getCheckListBar" },
			{ "query", "getAdtRstLineByAdtRptDate", "auditReport", "getAdtRstLineByAdtRptDate" },
			{ "query", "getAuditReportOperators", "auditReport", "getAuditReportOperators" },
			{ "query", "getAuditReportTargets", "auditReport", "getAuditReportTargets" },
			{ "query", "getAdtRstLineByTarget", "auditReport", "getAdtRstLineByTarget" },
			{ "query", "getAdtRstLineByProfession", "auditReport", "getAdtRstLineByProfession" },
			{ "query", "exportImproveIssueToExcel", "auditReport", "exportImproveIssueToExcel" },
			{ "query", "getOperatorForImproveIssue", "auditReport", "getOperatorForImproveIssue" },
			{ "query", "getTargetForImproveIssue", "auditReport", "getTargetForImproveIssue" },
			{ "query", "getCheckGradeForImproveIssue", "auditReport", "getCheckGradeForImproveIssue" },
			{ "query", "getPlanTypeForImproveIssue", "auditReport", "getPlanTypeForImproveIssue" },
			{ "query", "exportImproveIssueToPdf", "auditReport", "exportImproveIssueToPdf" },
			{ "modify", "confirmImproveIssue", "auditReport", "confirmImproveIssue" },
			// 审计工作流
			{ "query", "getAuditInfoType", "auditWorkflowScheme", "getAuditInfoType" },
			{ "modify", "addAuditWorkflowScheme", "auditWorkflowScheme", "addAuditWorkflowScheme" },
			{"modify","pushActivity","losa","pushActivity"},
			{"modify","pushActivities","losa","pushActivities"},
			{"query","pullActivity","losa","pullActivity"},
			{"query","queryFileList","losa","queryFileList"},
			{"query","pullActivities","losa","pullActivities"},
			{"query","queryActUpdateTime","losa","queryActUpdateTime"},
			{"query","queryActsUpdateTime","losa","queryActsUpdateTime"},
			{"query","queryBaseInfo","losa","queryBaseInfo"},
			{"query","downloadLosaFiles","losa","downloadFiles"},
			{"query","queryAttach","losa","queryAttach"},
			{"query","pullByInsertFieldType","losa","pullByInsertFieldType"},
			{ "modify", "uploadFile", "losa", "uploadFile" },
			{ "modify", "deleteFile", "losa", "deleteFile" },
			{ "modify", "deleteAttachFile", "losa", "deleteAttachFile" },
			{ "modify", "submitLosa", "losa", "submitLosa" },
			{ "modify", "deleteThreatManage", "losa", "deleteThreatManage" },
			{ "modify", "deleteErrorManage", "losa", "deleteErrorManage" },
			
			//Eiosa审计
			{"query","queryIsarps","iosaSection","queryIsarps"},
			{"query","queryIsarpsNew","iosaSection","queryIsarpsNew"},
			{"query","queryIsarpsDirectChildren","iosaSection","queryIsarpsDirectChildren"},
			{"query","querySection","iosaSection","querySection"},
			{"query","querySectionDtatil","iosaSection","querySectionDtatil"},
			{"query","queryDocuments","eiosaDocumentService","queryDocuments"},
			{"query","queryActions","iosaSection","queryActions"},
			{"query","queryAction","iosaSection","queryAction"},
			{"query","getSectionName","iosaSection","getSectionName"},
			{"query","queryUser","iosaSection","queryUser"},
			{"query","queryLog","iosaSection","queryLog"},
			{"query","queryIsarpNo","iosaSection","queryIsarpNo"},
			{"query","queryLogSender","iosaSection","queryLogSender"},
			{"query","queryLogReceiver","iosaSection","queryLogReceiver"},
			{"query","exportReport","iosaSection","exportReport"},
			{"query","queryAuditors","iosaSection","queryAuditors"},
			{"query","queryDocReviewed","iosaSection","queryDocReviewed"},
			{"query","checkUserRole","iosaSection","checkUserRole"},
			
			{"modify","isarpSubmit","iosaSection","isarpSubmit"},
			{"modify","reform","iosaSection","reform"},
			{"modify","updateActions","iosaSection","updateActions"},
			{"modify","updateIsarp","iosaSection","updateIsarp"},
			{"modify","addDealer","iosaSection","addDealer"},
			{"modify","updateChiefAuditor","iosaSection","updateChiefAuditor"},
			
			{"query","queryDocuments","eiosaDocumentService","queryDocuments"},
			{"query","queryAcronyms","eiosaDocumentService","queryAcronyms"},
			{"query","queryDocumentsByIsarp","eiosaDocumentService","queryDocumentsByIsarp"},
			{"query","queryDocumentsByReport","eiosaDocumentService","queryDocumentsByReport"},
			{"query","getEiosaDocumentById","eiosaDocumentService","getById"},
			
			
			{"modify","addDocumentSection","eiosaDocumentService","addDocumentSection"},
			{"modify","delDocumentSection","eiosaDocumentService","delDocumentSection"},
			{"modify","delEiosaDocument","eiosaDocumentService","delDocument"},
			{"modify","updateDocuments","eiosaDocumentService","updateDocuments"},
			
			{"query","getIsarpFull","isarpService","getIsarpFull"},
			{"query","queryIsarpCharpter","isarpService","queryIsarpCharpter"},
			{"query","queryIsarpIdBySectionChapter","isarpService","queryIsarpIdBySectionChapter"},
			{"query","queryConfirmityBySectionChapter","isarpService","queryConfirmityBySectionChapter"},
			{"query","queryConfirmityBySectionChapterWithSuffix","isarpService","queryConfirmityBySectionChapterWithSuffix"},
			{"query","testIsTable2_3_confirmity","isarpService","testIsTableConfirmity"},
			{"modify","reAudit","isarpService","reAudit"},
						
			{"modify","saveMessage","operateLogService","saveMessage"},
			
			{ "query", "getEiosaUsers", "eiosaUserService", "getEiosaUsers" },
			{ "query", "getEiosaUsersRole", "eiosaUserService", "getEiosaUsersRole" },

			{ "query", "sectionStatusReports", "reportService", "sectionStatusReports" },
			{ "query", "queryReportDtatil", "reportService", "queryReportDtatil" },
			{ "query", "exportisarpCharpterToPdf", "reportService", "exportisarpCharpterToPdf" },
			{ "query", "queryReport", "reportService", "queryReport" },
			
			//
			{ "query", "conformanceReports", "reportService", "conformanceReports" },
      { "query", "isarpCharpterReports", "reportService", "isarpCharpterReports" },
			{ "query", "ismWord", "reportService", "ismWord" },
			{ "query", "ismItemReport", "reportService", "ismItemReport" }, 
			{ "query", "checkDocumentIosa", "eiosaDocumentService", "checkDocumentIosa" },
			{ "query", "queryReportId", "iosaSection", "queryReportId" },
			{ "query", "queryReportIdAndEdition", "iosaSection", "queryReportIdAndEdition" },
			{ "query", "ismCeaWord", "reportService", "ismCeaWord" },
			{ "query", "queryThreatEvent", "threatEventService", "queryThreatEvent" },
			{ "query", "saveThreatEvent", "threatEventService", "saveThreatEvent" },
			{ "query", "deletedThreatEvent", "threatEventService", "deletedThreatEvent" },
			{ "query", "addThreatEvent", "threatEventService", "addThreatEvent" },
			{ "query", "queryScoreTemplet", "scoreTempletService", "queryScoreTemplet" },
			{ "query", "saveScoreTemplet", "scoreTempletService", "saveScoreTemplet" },
			{ "query", "querySort", "scoreTempletService", "querySort" },
			{ "query", "deletedScoreTemplet", "scoreTempletService", "deletedScoreTemplet" },
			{ "query", "addScoreTemplet", "scoreTempletService", "addScoreTemplet" },			
			{ "query", "queryFullTimeCaptain", "reportLosaService", "queryFullTimeCaptain" },
			{ "query", "queryThreatPercent", "reportLosaService", "queryThreatPercent" },
			{ "query", "queryThreatTop5", "reportLosaService", "queryThreatTop5" },
			{ "query", "queryErrorPercent", "reportLosaService", "queryErrorPercent" },
			{ "query", "queryErrorNamePercent10", "reportLosaService", "queryErrorNamePercent10" },
			{ "query", "queryErrorNameTop5", "reportLosaService", "queryErrorNameTop5" },


			{"modify","updateReport","reportService","updateReport"},
			
			//losa审计
			{"query","queryTaskPlan","taskPlanService","queryTaskPlan"},
			{"query","queryDictNames","dictTypeService","queryDictNames"},
			{"query","queryDuty","dictTypeService","queryDuty"},
			{"query","querySchemes","schemeService","querySchemes"},
			{"query","queryThreadType","threatBaseInfoService","queryThreadType"},
			{"query","queryThreadNo","threatBaseInfoService","queryThreadNo"},
			{ "modify", "saveTaskPlan", "taskPlanService", "saveTaskPlan" },
			{"modify","delTaskPlan","taskPlanService","delTaskPlan"},
			{"modify","modifyTaskPlan","taskPlanService","modifyTaskPlan"},
			{"query","losaGetAirPort","taskPlanService","getAirportByNameAndIATACode"},
			{"query","losaQueryMulFly","taskPlanService","queryMulFly"},
			{"modify", "losaSavePlanByFlightId", "taskPlanService", "savePlanByFlightId"},
			{"modify", "losaDelPlanByFlightId", "taskPlanService", "delPlanByFlightId"},
			{"query","losaQueryDetailFly","taskPlanService","queryDetailFly"},
			{"modify", "losaDelPlanByTask", "taskPlanService", "delPlanByTask"},
			{"modify", "losaSavePlanByTask", "taskPlanService", "savePlanByTask"},
			{"query","losaGetFlightUnitNameAndCode","taskPlanService","getFlightUnitNameAndCode"},
			{"query","losaQueryFlightInfo","taskPlanService","queryFlightInfo"},
			{"query","losaQuerySchemeImpleUnit","schemeService","querySchemeImpleUnit"},
			{"modify", "losaInsertOrUpdateScheme", "schemeService", "insertOrUpdateScheme"},
			{"modify", "losaDelSchemes", "schemeService", "delSchemes"},
			{"query","losaQueryLosaAuditors","taskPlanService","queryLosaAuditors"},
			{"query","losaGetUserAuth","schemeService","getUserAuth"},			
			{"query","losaIsUserSchemeUnit","schemeService","isUserSchemeUnit"},
			{"modify","losaDisSchemes","schemeService","disSchemes"},
			{"query","losaQuerySchemeInfoById","schemeService","querySchemeInfoById"},
			{"query","queryThreatErrorCount","reportLosaService","queryThreatErrorCount"},
			{"query","ExportangerCount","reportLosaService","ExportangerCount"},
			{"query","queryThreatDetail","reportLosaService","queryThreatDetail"},
			{"query","exportThreatDetail","reportLosaService","exportThreatDetail"},
			{"query","queryErrorDetail","reportLosaService","queryErrorDetail"},
			{"query","exportErrorDetail","reportLosaService","exportErrorDetail"},
			{"query","losaGetUserAuths","reportLosaService","getUserAuths"},
			{"query","querySchemeOrgcode","reportLosaService","querySchemeOrgcode"},
			{"query","queryPlanFlightInfo","taskPlanService","queryPlanFlightInfo"},
			{"query","observerInfoService","observerInfoService","observerInfoServiceInit"},
			{"query","getRiskColour","threat","getRiskColour"},
			{"modify","updateRiskTwoLevels","threat","updateRiskTwoLevels"},
			{"modify","sendShortMessage","shortMessage","sendShortMessage"},
	 };
}
