package com.junyao.sms.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-11-04T14:39:44.533+08:00
 * Generated source version: 3.1.8
 * 
 */
@WebServiceClient(name = "JwSmsServiceImplService", 
                  wsdlLocation = "file:/D:/Administrator/Documents/workspace_eclipse/smsmain/sms/src/main/resources/机务接口说明.wsdl",
                  targetNamespace = "http://service.sms.junyao.com/") 
public class JwSmsServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.sms.junyao.com/", "JwSmsServiceImplService");
    public final static QName JwSmsServiceImplPort = new QName("http://service.sms.junyao.com/", "JwSmsServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/Administrator/Documents/workspace_eclipse/smsmain/sms/src/main/resources/机务接口说明.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(JwSmsServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/Administrator/Documents/workspace_eclipse/smsmain/sms/src/main/resources/机务接口说明.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public JwSmsServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public JwSmsServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JwSmsServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public JwSmsServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public JwSmsServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public JwSmsServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns JwSmsService
     */
    @WebEndpoint(name = "JwSmsServiceImplPort")
    public JwSmsService getJwSmsServiceImplPort() {
        return super.getPort(JwSmsServiceImplPort, JwSmsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JwSmsService
     */
    @WebEndpoint(name = "JwSmsServiceImplPort")
    public JwSmsService getJwSmsServiceImplPort(WebServiceFeature... features) {
        return super.getPort(JwSmsServiceImplPort, JwSmsService.class, features);
    }

}
